# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='the_wall.MessagePost'),
        ),
    ]
